### ISSUE TITLE
Phone Donation Edit Model changes

### ISSUE THREAD

**Issue by topherwhite** [rfcx/rfcx.org#10]
Looks good so far! Here are a bunch of changes to make. See the image pasted below, along with some explanations in advance.

The changes mostly involve alterations of the field labels and reorganization of their placement/size.

Also, some of the fields should be read-only (specified) and the date of donation should be a date picker (auto-formatted to the date format that mailchimp expects)

Finally for the "ID", the fact that it's an email address is not really something that needs to be shown. Please hide the "@rfcx.org" from the field value that's shown (and also please make it read only)

![image](https://cloud.githubusercontent.com/assets/1895255/10915862/70a4991a-8237-11e5-9c3f-e5712e1593ad.png)

**Comment by rassokhin-s** [comment]
Questions for @topherwhite :
1) Donation ID. Maybe we also need to cut it to stay only first 6 letters? (This is what we show to our donor on the frontend page).
2) Donor email is now read-only. Should I set it editable?
3) You marked Donor Notes as read-only, but it's already read-only. Should I update smth?
4) After admin uploaded a photo, an image preview is available for review (see attached). Should I stay it and where it should be placed on the new design?
<img width="586" alt="2015-11-03 20 44 50" src="https://cloud.githubusercontent.com/assets/2122991/10916322/fffb926a-826b-11e5-90e2-cffb1e9d0e04.png">

**Comment by rassokhin-s** [comment]
Feedback from Topher:
1) Let’s keep all the digits.
2) Donor email should be editable, in case a donor gives us a different (better) email address in the package they send.
3) No changes here.
4) Keep image preview on the same place as earlier.

**Comment by rassokhin-s** [comment]
@topherwhite updated in 816d8af4651f1158163508e5538de4a4b98b95e7 and 783259326e001bc2fa88b4b63504d5731691ee88
