### ISSUE TITLE
Add reference to github account

### ISSUE THREAD

**Issue by leobel96** [rfcx/rfcx.org#14]
On the website there is no reference to GitHub account so there is no way to know that everything is on GitHub. Please add a link to GitHub in footer and in "Get Involved" section.

**Comment by antonyharfield** [comment]
Thanks for the suggestion @leobel96 and sorry we have been slow to respond. As you may have noticed, the website is out-of-date and needs quite a lot of love. I have added the Github link to the footer, but further changes on Get Involved are on-hold until we have a plan for renovating the entire site.
