### ISSUE TITLE
Critical Content Line to Add

### ISSUE THREAD

**Issue by davegin** [rfcx/rfcx.org#5]
Rainforest Connection is working on multi-tiered platforms for remote sensing of ecological data that can be used to monitor the health of forests and endangered species. 

(Note: We want to add this line somewhere on the website, so our audience knows our black box and pathway to success is broader than just real-time, broader than just chainsaws, destruction and is more general... this sentence or some version encapsulates all future uses including bio-monitoring.)

**Comment by topherwhite** [comment]
Done
