### ISSUE TITLE
Setup MailChimp to be the primary storage point for donor submissions

### ISSUE THREAD

**Issue by topherwhite** [rfcx/rfcx.org#7]
To discuss...

**Comment by Debjani1989** [comment]
Hello Topher, is there anything you want to discuss with me?

**Comment by Debjani1989** [comment]
Hello Topher,

Have you checked the map work? Wanna talk to you about the upcoming
project.

Debjani

**Comment by topherwhite** [comment]
This is done, and working. Thanks!
