### ISSUE TITLE
Phone Donation: If "save/submit" request fails, we need to generate a new recaptcha code

### ISSUE THREAD

**Issue by topherwhite** [rfcx/rfcx.org#8]
While testing over a slow/unreliable connection, I frequently encountered failed save requests. This is not a problem with the application, but rather a problem with my internet connection, however...

After a failed request, the page still uses the same recaptcha code with the AJAX submit request. This is rejected by the server. 

So, when a save request fails over AJAX, we still need to ask the the user to re-do the captcha before submission, with a new code, otherwise the request will also be rejected the next time they try to submit.

I hope that makes sense! Thanks

**Comment by rassokhin-s** [comment]
@topherwhite cannot reproduce such issue, but I've added recaptcha reset if error response returned. Check please.
